### ISSUE TITLE
[BUG] state.apply fails on unconfigured pillar

### ISSUE THREAD

**Issue by matt-gnu** [saltstack-formulas/fail2ban-formula#41]
### Formula commit hash / release tag

459792219f86a19081addb4dec64bb5444b2ef8d

### Versions reports (master & minion)

# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12 

### Pillar / config used

dry-running
`salt '<hostname>' state.apply fail2ban.service --state-verbose=False  --state-output=mixed  test=True`

---

### Describe the bug

```
<hostname>:
----------
          ID: fail2ban.config.jails
    Function: file.absent
      Result: False
     Comment: Specified file fail2ban.config.jails is not an absolute path
     Started: 15:32:51.260231
    Duration: 1.252 ms
     Changes:   
----------     
          ID: fail2ban.service
    Function: service.running
        Name: fail2ban
      Result: False
     Comment: One or more requisite failed: fail2ban.config.fail2ban.config.jails
     Started: 15:32:51.264728
    Duration: 0.014 ms
     Changes:   
               
```

### Expected behaviour

I expected some no-op or default behavior ;-)

### Attempts to fix the bug

Pull-request will follow.
