### ISSUE TITLE
[BUG] FreeBSD is failing trying to use 'root' group for config files

### ISSUE THREAD

**Issue by fzipi** [saltstack-formulas/fail2ban-formula#46]
### Formula commit hash / release tag

Latest master

### Versions reports (master & minion)

Salt v2019.2.5, python 3.7

### Pillar / config used

```
fail2ban:
  lookup:
    config:
      loglevel: INFO
      ignoreip: 127.0.0.1/8 other.ips
      bantime: 6000
      maxretry: 3
      backend: auto
    jails:
      local-sshd:
        enabled: 'true'
        filter: sshd
        mode: ddos
        logpath: /var/log/auth.log
        maxretry: 3
        port: ssh
        bantime: 86400
        banaction: pf[actiontype=<allports>]
```

---

### Describe the bug

```
       ----------
                 ID: fail2ban.install
           Function: pkg.installed
               Name: py37-fail2ban
             Result: True
            Comment: The following packages were installed/updated: py37-fail2ban
            Started: 05:29:04.374835
           Duration: 12037.881 ms
            Changes:   
              ----------
              py37-fail2ban:
                  ----------
                  new:
                      0.11.1_1
                  old:
              py37-sqlite3:
                  ----------
                  new:
                      3.7.9_7
                  old:
       ----------
                 ID: fail2ban.config.fail2ban
           Function: file.managed
               Name: /usr/local/etc/fail2ban/fail2ban.local
             Result: False
            Comment: Group root is not available
            Started: 05:29:16.416601
           Duration: 4.983 ms
            Changes:   
       ----------
```

### Steps to reproduce the bug

Just include the basics.

### Expected behaviour

Install and configure fail2ban.

### Attempts to fix the bug

I've sent PR #45 to fix the mapping.
