### ISSUE TITLE
2015.5.2 doesn't work anymore

### ISSUE THREAD

**Issue by lichtamberg** [saltstack-formulas/fail2ban-formula#8]
Worked before (2015.5.0), upgraded now to following and received this error:

``` shell
           Salt: 2015.5.2-112-g2d8148f
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.1
        Tornado: 4.1
```

``` salt
----------
          ID: /etc/fail2ban/fail2ban.local
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: 'NoneType' object is not iterable
              Traceback (most recent call last):
                File "/tmp/.deployer_85176d__salt/salt/utils/templates.py", line 306, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/tmp/.deployer_85176d__salt/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/tmp/.deployer_85176d__salt/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 25, in top-level template code
                File "<template>", line 13, in template
                File "/tmp/.deployer_85176d__salt/jinja2/filters.py", line 349, in do_first
                  return next(iter(seq))
              TypeError: 'NoneType' object is not iterable

              ; line 13

              ---
              [...]
              {{ name }} = {{ value }}
                  {%- elif value is number %}
              {{ name }} = {{ value }}
                  {%- else %}
                  {#- Since strings are also sequences, there's no way to explicitly test for lists #}
              {{ name }} = {{ value|first }}    <======================
                      {%- if value|length > 1 %}
                          {%- for item in value[1:] %}
              {{ item|indent(width=name_length + 3, indentfirst=True) }}
                          {%- endfor %}
                      {%- endif %}
              [...]
              ---
     Started: 15:17:54.539948
    Duration: 19.021 ms
     Changes:
----------
          ID: fail2ban
    Function: service.running
      Result: False
     Comment: One or more requisite failed: fail2ban.config./etc/fail2ban/fail2ban.local
     Started:
    Duration:
     Changes:
```

Pillar: 

``` yaml
fail2ban:
    lookup:
        config:
            loglevel: 2
            ignoreip: 127.0.0.1/8
            bantime: 12000
            maxretry: 3
            backend: auto
            destemail: {{ salt["pillar.get"]('base:admin_email') }}
            sendername: "'{{ salt["pillar.get"]('base:domain') }} - Fail2Ban'"
            mta: sendmail
            action: 
              - action_mwl
        jails:
            ssh:
                action:
                    - iptables-allports[name=SSH, port=ssh, protocol=tcp]
                    - sendmail-whois[name=SSH, dest={{ salt["pillar.get"]('base:admin_email') }}, sender=fail2ban@{{ salt["pillar.get"]('base:domain') }}]
                enabled: 'true'
                filter: sshd
                logpath: /var/log/auth.log
                maxretry: 3
                port: all
            ssh_ddos:
                action:
                    - iptables-allports[name=SSH, port=ssh, protocol=tcp]
                enabled: 'false'
                filter: sshd-ddos
                logpath: /var/log/auth.log
                maxretry: 3
                port: all

```
